### ISSUE TITLE
Build broken due to private crates (and other issues)?

### ISSUE THREAD

**Issue by coolbluewater** [tanis2000/minigame-rust#11]
There are a couple of private crates in `cargo.toml`:

```
sdl2 = { path="../tanis2000-rust-sdl2", default-features = false, features = ["unsafe_textures"] }
tiled-json-rs = { path="../Santinelli-tiled-json-rs" }
```
I tried replacing these entries with those available in crates.io, but the build still fails with errors in build.rs.

As a rust newbie, that's as far as my debugging skills currently do. Would really appreciate a fix, this project will really bump up my rust knowledge once I get it building :)

I'm primarily interested in the iOS build, and secondarily in Mac/Windows. Thanks!

**Comment by tanis2000** [comment]
You stand correct. As a quick workaround you can replace the sdl2 location with this repo: https://github.com/tanis2000/rust-sdl2
The second line can be replaced with this project: https://gitlab.com/Santinelli/tiled-json-rs

**Comment by coolbluewater** [comment]
Thanks for the quick reply. I made further progress, with these steps:

1. Modified the iOS version from 12.2 => 13.2 in `build.rs`, since that is the version I have.

2. Built for `x86-64-apple-ios`. This succeeds:
```
cargo build --no-default-features --target x86_64-apple-ios --lib
```
2. Built for `aarch64-apple-ios`. This fails while building. The first two errors are below.
```
cargo build --no-default-features --target aarch64-apple-ios --lib
error: no rules expected the token `flags`
  --> src/collider.rs:88:5
   |
88 |     flags PointSectors: u8 {
   |     ^^^^^ no rules expected this token in macro call

error[E0412]: cannot find type `Plugins` in this scope
   --> src/engine.rs:651:57
    |
651 |     pub fn run_main_loop<'a>(&mut self, mut plugs: &mut Plugins, mut reload_handler: &mut DynamicReload<'a>) {
    |                                                         ^^^^^^^ not found in this scope
```

I wonder why the `aarch64` build is failing, when the `x86_64` build succeeds?

**Comment by coolbluewater** [comment]
Thanks! I deleted my earlier comment as I was able to checkout an build an earlier revision of the project (May 24). Since I'm only using this to learn, that's all I need. Cheers.
